{
  "openapi": "3.0.1",
  "info": {
    "title": "Schiphol",
    "version": "1.0.0",
    "description": ".",
    "contact": {
      "email": "max.van.kampen@alicon.nl"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "termsOfService": "https://schiphol.aliconnect.nl/terms/"
  },
  "servers": [
    {
      "url": "https://aliconnect.nl"
    }
  ],
  "paths": {
    "/js": {
      "get": {
        "operationId": "/aim/js",
        "security": [
          {
            "aliconnect_auth": [
              "read:web"
            ]
          }
        ]
      }
    },
    "/login": {
      "get": {
        "operationId": "/aim/",
        "security": [
          {
            "aliconnect_auth": [
              "read:web"
            ]
          }
        ]
      }
    },
    "/": {
      "get": {
        "operationId": "def.get"
      },
      "post": {
        "operationId": "def.post",
        "security": [
          {
            "aim_auth": [
              "admin.readwrite"
            ]
          }
        ]
      }
    },
    "/account": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "operationId": "account.post",
        "security": [
          {
            "aim_auth": [
              "admin.readwrite"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Authentication"
        ],
        "operationId": "account.patch",
        "security": [
          {
            "aim_auth": [
              "admin.readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Authentication"
        ],
        "operationId": "account.delete",
        "security": [
          {
            "aim_auth": [
              "admin.readwrite"
            ]
          }
        ]
      }
    },
    "/file({id})": {
      "patch": {
        "tags": [
          "Files"
        ],
        "summary": "Updates a file",
        "operationId": "file_patch",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Files"
        ],
        "summary": "Deletes a file",
        "operationId": "file_delete",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Company": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get list of Company",
        "operationId": "item(Company).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Add a new Company",
        "operationId": "Item(Company).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Company({id})": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Find Company by ID",
        "description": "Returns a single Company object",
        "operationId": "Item(Company,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Updates a Company with form data",
        "operationId": "Item(Company,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Company"
        ],
        "summary": "Updates a Company",
        "operationId": "Item(Company,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Company"
        ],
        "summary": "Deletes a Company",
        "operationId": "Item(Company,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Company({id})/file": {
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Adds an attachement to a Company object with form data",
        "operationId": "Item(Company,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Company({id})/children": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get children of Company object by ID",
        "description": "Returns all child objects of a Company object",
        "operationId": "Item(Company,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Company({id})/references": {
      "get": {
        "tags": [
          "Company"
        ],
        "summary": "Get children of Company object by ID",
        "description": "Returns all child objects of a Company object",
        "operationId": "Item(Company,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Company({id})/Employees": {
      "get": {
        "tags": [
          "Company",
          "Contact"
        ],
        "summary": "Find Company by ID and selects all of schema Contact",
        "description": "Returns a list of Employees",
        "operationId": "Item(Company,id).link(Employees,get)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Company"
        ],
        "summary": "Adds an attachement to a Company object with form data",
        "operationId": "Item(Company,id).link(Employees,post)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Company({id})/Employees({linkId})": {
      "delete": {
        "tags": [
          "Company",
          "Contact"
        ],
        "summary": "Find Company by ID and selects all of schema Contact",
        "description": "Returns a list of Employees",
        "operationId": "Item(Company,id).link(Employees,delete)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Get list of Contact",
        "operationId": "item(Contact).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Add a new Contact",
        "operationId": "Item(Contact).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact({id})": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Find Contact by ID",
        "description": "Returns a single Contact object",
        "operationId": "Item(Contact,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Updates a Contact with form data",
        "operationId": "Item(Contact,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Contact"
        ],
        "summary": "Updates a Contact",
        "operationId": "Item(Contact,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Contact"
        ],
        "summary": "Deletes a Contact",
        "operationId": "Item(Contact,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact({id})/file": {
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Adds an attachement to a Contact object with form data",
        "operationId": "Item(Contact,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Contact({id})/children": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Get children of Contact object by ID",
        "description": "Returns all child objects of a Contact object",
        "operationId": "Item(Contact,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact({id})/references": {
      "get": {
        "tags": [
          "Contact"
        ],
        "summary": "Get children of Contact object by ID",
        "description": "Returns all child objects of a Contact object",
        "operationId": "Item(Contact,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact({id})/Product": {
      "get": {
        "tags": [
          "Contact",
          "System"
        ],
        "summary": "Find Contact by ID and selects all of schema System",
        "description": "Returns a list of Product",
        "operationId": "Item(Contact,id).link(Product,get)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Contact"
        ],
        "summary": "Adds an attachement to a Contact object with form data",
        "operationId": "Item(Contact,id).link(Product,post)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Contact({id})/Product({linkId})": {
      "delete": {
        "tags": [
          "Contact",
          "System"
        ],
        "summary": "Find Contact by ID and selects all of schema System",
        "description": "Returns a list of Product",
        "operationId": "Item(Contact,id).link(Product,delete)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Map": {
      "get": {
        "tags": [
          "Map"
        ],
        "summary": "Get list of Map",
        "operationId": "item(Map).find",
        "security": [
          {
            "api_key": [
              "map.read"
            ]
          },
          {
            "aim_auth": [
              "map.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Map"
        ],
        "summary": "Add a new Map",
        "operationId": "Item(Map).add",
        "security": [
          {
            "api_key": [
              "map.readwrite"
            ]
          },
          {
            "aim_auth": [
              "map.readwrite"
            ]
          }
        ]
      }
    },
    "/Website": {
      "get": {
        "tags": [
          "Website"
        ],
        "summary": "Get list of Website",
        "operationId": "item(Website).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Website"
        ],
        "summary": "Add a new Website",
        "operationId": "Item(Website).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Website({id})": {
      "get": {
        "tags": [
          "Website"
        ],
        "summary": "Find Website by ID",
        "description": "Returns a single Website object",
        "operationId": "Item(Website,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Website"
        ],
        "summary": "Updates a Website with form data",
        "operationId": "Item(Website,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Website"
        ],
        "summary": "Updates a Website",
        "operationId": "Item(Website,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Website"
        ],
        "summary": "Deletes a Website",
        "operationId": "Item(Website,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Website({id})/file": {
      "post": {
        "tags": [
          "Website"
        ],
        "summary": "Adds an attachement to a Website object with form data",
        "operationId": "Item(Website,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Website({id})/children": {
      "get": {
        "tags": [
          "Website"
        ],
        "summary": "Get children of Website object by ID",
        "description": "Returns all child objects of a Website object",
        "operationId": "Item(Website,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Website({id})/references": {
      "get": {
        "tags": [
          "Website"
        ],
        "summary": "Get children of Website object by ID",
        "description": "Returns all child objects of a Website object",
        "operationId": "Item(Website,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage": {
      "get": {
        "tags": [
          "Webpage"
        ],
        "summary": "Get list of Webpage",
        "operationId": "item(Webpage).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webpage"
        ],
        "summary": "Add a new Webpage",
        "operationId": "Item(Webpage).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage({id})": {
      "get": {
        "tags": [
          "Webpage"
        ],
        "summary": "Find Webpage by ID",
        "description": "Returns a single Webpage object",
        "operationId": "Item(Webpage,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webpage"
        ],
        "summary": "Updates a Webpage with form data",
        "operationId": "Item(Webpage,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Webpage"
        ],
        "summary": "Updates a Webpage",
        "operationId": "Item(Webpage,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webpage"
        ],
        "summary": "Deletes a Webpage",
        "operationId": "Item(Webpage,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage({id})/file": {
      "post": {
        "tags": [
          "Webpage"
        ],
        "summary": "Adds an attachement to a Webpage object with form data",
        "operationId": "Item(Webpage,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Webpage({id})/children": {
      "get": {
        "tags": [
          "Webpage"
        ],
        "summary": "Get children of Webpage object by ID",
        "description": "Returns all child objects of a Webpage object",
        "operationId": "Item(Webpage,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage({id})/references": {
      "get": {
        "tags": [
          "Webpage"
        ],
        "summary": "Get children of Webpage object by ID",
        "description": "Returns all child objects of a Webpage object",
        "operationId": "Item(Webpage,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage({id})/Webpage": {
      "get": {
        "tags": [
          "Webpage",
          "Webpage"
        ],
        "summary": "Find Webpage by ID and selects all of schema Webpage",
        "description": "Returns a list of Webpage",
        "operationId": "Item(Webpage,id).link(Webpage,get)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webpage"
        ],
        "summary": "Adds an attachement to a Webpage object with form data",
        "operationId": "Item(Webpage,id).link(Webpage,post)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Webpage({id})/Webpage({linkId})": {
      "delete": {
        "tags": [
          "Webpage",
          "Webpage"
        ],
        "summary": "Find Webpage by ID and selects all of schema Webpage",
        "description": "Returns a list of Webpage",
        "operationId": "Item(Webpage,id).link(Webpage,delete)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Schema": {
      "get": {
        "tags": [
          "Schema"
        ],
        "summary": "Get list of Schema",
        "operationId": "item(Schema).find",
        "security": [
          {
            "api_key": [
              "schema.read"
            ]
          },
          {
            "aim_auth": [
              "schema.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Schema"
        ],
        "summary": "Add a new Schema",
        "operationId": "Item(Schema).add",
        "security": [
          {
            "api_key": [
              "schema.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schema.readwrite"
            ]
          }
        ]
      }
    },
    "/Schema({id})": {
      "get": {
        "tags": [
          "Schema"
        ],
        "summary": "Find Schema by ID",
        "description": "Returns a single Schema object",
        "operationId": "Item(Schema,id).get",
        "security": [
          {
            "api_key": [
              "schema.read"
            ]
          },
          {
            "aim_auth": [
              "schema.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Schema"
        ],
        "summary": "Updates a Schema with form data",
        "operationId": "Item(Schema,id).post",
        "security": [
          {
            "api_key": [
              "schema.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schema.readwrite"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Schema"
        ],
        "summary": "Updates a Schema",
        "operationId": "Item(Schema,id).patch",
        "security": [
          {
            "api_key": [
              "schema.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schema.readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Schema"
        ],
        "summary": "Deletes a Schema",
        "operationId": "Item(Schema,id).delete",
        "security": [
          {
            "api_key": [
              "schema.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schema.readwrite"
            ]
          }
        ]
      }
    },
    "/Schema({id})/file": {
      "post": {
        "tags": [
          "Schema"
        ],
        "summary": "Adds an attachement to a Schema object with form data",
        "operationId": "Item(Schema,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Schema({id})/children": {
      "get": {
        "tags": [
          "Schema"
        ],
        "summary": "Get children of Schema object by ID",
        "description": "Returns all child objects of a Schema object",
        "operationId": "Item(Schema,id).children()",
        "security": [
          {
            "api_key": [
              "schema.read"
            ]
          },
          {
            "aim_auth": [
              "schema.read"
            ]
          }
        ]
      }
    },
    "/Schema({id})/references": {
      "get": {
        "tags": [
          "Schema"
        ],
        "summary": "Get children of Schema object by ID",
        "description": "Returns all child objects of a Schema object",
        "operationId": "Item(Schema,id).references()",
        "security": [
          {
            "api_key": [
              "schema.read"
            ]
          },
          {
            "aim_auth": [
              "schema.read"
            ]
          }
        ]
      }
    },
    "/Message": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Get list of Message",
        "operationId": "item(Message).find",
        "security": [
          {
            "api_key": [
              "message.read"
            ]
          },
          {
            "aim_auth": [
              "message.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Add a new Message",
        "operationId": "Item(Message).add",
        "security": [
          {
            "api_key": [
              "message.readwrite"
            ]
          },
          {
            "aim_auth": [
              "message.readwrite"
            ]
          }
        ]
      }
    },
    "/Message({id})": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Find Message by ID",
        "description": "Returns a single Message object",
        "operationId": "Item(Message,id).get",
        "security": [
          {
            "api_key": [
              "message.read"
            ]
          },
          {
            "aim_auth": [
              "message.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Updates a Message with form data",
        "operationId": "Item(Message,id).post",
        "security": [
          {
            "api_key": [
              "message.readwrite"
            ]
          },
          {
            "aim_auth": [
              "message.readwrite"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Message"
        ],
        "summary": "Updates a Message",
        "operationId": "Item(Message,id).patch",
        "security": [
          {
            "api_key": [
              "message.readwrite"
            ]
          },
          {
            "aim_auth": [
              "message.readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Message"
        ],
        "summary": "Deletes a Message",
        "operationId": "Item(Message,id).delete",
        "security": [
          {
            "api_key": [
              "message.readwrite"
            ]
          },
          {
            "aim_auth": [
              "message.readwrite"
            ]
          }
        ]
      }
    },
    "/Message({id})/file": {
      "post": {
        "tags": [
          "Message"
        ],
        "summary": "Adds an attachement to a Message object with form data",
        "operationId": "Item(Message,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Message({id})/children": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Get children of Message object by ID",
        "description": "Returns all child objects of a Message object",
        "operationId": "Item(Message,id).children()",
        "security": [
          {
            "api_key": [
              "message.read"
            ]
          },
          {
            "aim_auth": [
              "message.read"
            ]
          }
        ]
      }
    },
    "/Message({id})/references": {
      "get": {
        "tags": [
          "Message"
        ],
        "summary": "Get children of Message object by ID",
        "description": "Returns all child objects of a Message object",
        "operationId": "Item(Message,id).references()",
        "security": [
          {
            "api_key": [
              "message.read"
            ]
          },
          {
            "aim_auth": [
              "message.read"
            ]
          }
        ]
      }
    },
    "/Schakelbericht": {
      "get": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Get list of Schakelbericht",
        "operationId": "item(Schakelbericht).find",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Add a new Schakelbericht",
        "operationId": "Item(Schakelbericht).add",
        "security": [
          {
            "api_key": [
              "schakelbericht.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.readwrite"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})": {
      "get": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Find Schakelbericht by ID",
        "description": "Returns a single Schakelbericht object",
        "operationId": "Item(Schakelbericht,id).get",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Updates a Schakelbericht with form data",
        "operationId": "Item(Schakelbericht,id).post",
        "security": [
          {
            "api_key": [
              "schakelbericht.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.readwrite"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Updates a Schakelbericht",
        "operationId": "Item(Schakelbericht,id).patch",
        "security": [
          {
            "api_key": [
              "schakelbericht.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.readwrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Deletes a Schakelbericht",
        "operationId": "Item(Schakelbericht,id).delete",
        "security": [
          {
            "api_key": [
              "schakelbericht.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.readwrite"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})/file": {
      "post": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Adds an attachement to a Schakelbericht object with form data",
        "operationId": "Item(Schakelbericht,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})/children": {
      "get": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Get children of Schakelbericht object by ID",
        "description": "Returns all child objects of a Schakelbericht object",
        "operationId": "Item(Schakelbericht,id).children()",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})/references": {
      "get": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Get children of Schakelbericht object by ID",
        "description": "Returns all child objects of a Schakelbericht object",
        "operationId": "Item(Schakelbericht,id).references()",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})/Messages": {
      "get": {
        "tags": [
          "Schakelbericht",
          "Message"
        ],
        "summary": "Find Schakelbericht by ID and selects all of schema Message",
        "description": "Returns a list of Messages",
        "operationId": "Item(Schakelbericht,id).link(Messages,get)",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Schakelbericht"
        ],
        "summary": "Adds an attachement to a Schakelbericht object with form data",
        "operationId": "Item(Schakelbericht,id).link(Messages,post)",
        "security": [
          {
            "api_key": [
              "schakelbericht.readwrite"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.readwrite"
            ]
          }
        ]
      }
    },
    "/Schakelbericht({id})/Messages({linkId})": {
      "delete": {
        "tags": [
          "Schakelbericht",
          "Message"
        ],
        "summary": "Find Schakelbericht by ID and selects all of schema Message",
        "description": "Returns a list of Messages",
        "operationId": "Item(Schakelbericht,id).link(Messages,delete)",
        "security": [
          {
            "api_key": [
              "schakelbericht.read"
            ]
          },
          {
            "aim_auth": [
              "schakelbericht.read"
            ]
          }
        ]
      }
    },
    "/System": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Get list of System",
        "operationId": "item(System).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "System"
        ],
        "summary": "Add a new System",
        "operationId": "Item(System).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/System({id})": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Find System by ID",
        "description": "Returns a single System object",
        "operationId": "Item(System,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "System"
        ],
        "summary": "Updates a System with form data",
        "operationId": "Item(System,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "System"
        ],
        "summary": "Updates a System",
        "operationId": "Item(System,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "System"
        ],
        "summary": "Deletes a System",
        "operationId": "Item(System,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/System({id})/file": {
      "post": {
        "tags": [
          "System"
        ],
        "summary": "Adds an attachement to a System object with form data",
        "operationId": "Item(System,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/System({id})/children": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Get children of System object by ID",
        "description": "Returns all child objects of a System object",
        "operationId": "Item(System,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/System({id})/references": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Get children of System object by ID",
        "description": "Returns all child objects of a System object",
        "operationId": "Item(System,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Attribute": {
      "get": {
        "tags": [
          "Attribute"
        ],
        "summary": "Get list of Attribute",
        "operationId": "item(Attribute).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Attribute"
        ],
        "summary": "Add a new Attribute",
        "operationId": "Item(Attribute).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Attribute({id})": {
      "get": {
        "tags": [
          "Attribute"
        ],
        "summary": "Find Attribute by ID",
        "description": "Returns a single Attribute object",
        "operationId": "Item(Attribute,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Attribute"
        ],
        "summary": "Updates a Attribute with form data",
        "operationId": "Item(Attribute,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Attribute"
        ],
        "summary": "Updates a Attribute",
        "operationId": "Item(Attribute,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Attribute"
        ],
        "summary": "Deletes a Attribute",
        "operationId": "Item(Attribute,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Attribute({id})/file": {
      "post": {
        "tags": [
          "Attribute"
        ],
        "summary": "Adds an attachement to a Attribute object with form data",
        "operationId": "Item(Attribute,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Attribute({id})/children": {
      "get": {
        "tags": [
          "Attribute"
        ],
        "summary": "Get children of Attribute object by ID",
        "description": "Returns all child objects of a Attribute object",
        "operationId": "Item(Attribute,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Attribute({id})/references": {
      "get": {
        "tags": [
          "Attribute"
        ],
        "summary": "Get children of Attribute object by ID",
        "description": "Returns all child objects of a Attribute object",
        "operationId": "Item(Attribute,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/ControlIO": {
      "get": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Get list of ControlIO",
        "operationId": "item(ControlIO).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Add a new ControlIO",
        "operationId": "Item(ControlIO).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/ControlIO({id})": {
      "get": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Find ControlIO by ID",
        "description": "Returns a single ControlIO object",
        "operationId": "Item(ControlIO,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Updates a ControlIO with form data",
        "operationId": "Item(ControlIO,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Updates a ControlIO",
        "operationId": "Item(ControlIO,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Deletes a ControlIO",
        "operationId": "Item(ControlIO,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/ControlIO({id})/file": {
      "post": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Adds an attachement to a ControlIO object with form data",
        "operationId": "Item(ControlIO,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/ControlIO({id})/children": {
      "get": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Get children of ControlIO object by ID",
        "description": "Returns all child objects of a ControlIO object",
        "operationId": "Item(ControlIO,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/ControlIO({id})/references": {
      "get": {
        "tags": [
          "ControlIO"
        ],
        "summary": "Get children of ControlIO object by ID",
        "description": "Returns all child objects of a ControlIO object",
        "operationId": "Item(ControlIO,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Device": {
      "get": {
        "tags": [
          "Device"
        ],
        "summary": "Get list of Device",
        "operationId": "item(Device).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Device"
        ],
        "summary": "Add a new Device",
        "operationId": "Item(Device).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Device({id})": {
      "get": {
        "tags": [
          "Device"
        ],
        "summary": "Find Device by ID",
        "description": "Returns a single Device object",
        "operationId": "Item(Device,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Device"
        ],
        "summary": "Updates a Device with form data",
        "operationId": "Item(Device,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Device"
        ],
        "summary": "Updates a Device",
        "operationId": "Item(Device,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Device"
        ],
        "summary": "Deletes a Device",
        "operationId": "Item(Device,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Device({id})/file": {
      "post": {
        "tags": [
          "Device"
        ],
        "summary": "Adds an attachement to a Device object with form data",
        "operationId": "Item(Device,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Device({id})/children": {
      "get": {
        "tags": [
          "Device"
        ],
        "summary": "Get children of Device object by ID",
        "description": "Returns all child objects of a Device object",
        "operationId": "Item(Device,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Device({id})/references": {
      "get": {
        "tags": [
          "Device"
        ],
        "summary": "Get children of Device object by ID",
        "description": "Returns all child objects of a Device object",
        "operationId": "Item(Device,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Product": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get list of Product",
        "operationId": "item(Product).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Add a new Product",
        "operationId": "Item(Product).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Product({id})": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Find Product by ID",
        "description": "Returns a single Product object",
        "operationId": "Item(Product,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Updates a Product with form data",
        "operationId": "Item(Product,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Product"
        ],
        "summary": "Updates a Product",
        "operationId": "Item(Product,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Product"
        ],
        "summary": "Deletes a Product",
        "operationId": "Item(Product,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Product({id})/file": {
      "post": {
        "tags": [
          "Product"
        ],
        "summary": "Adds an attachement to a Product object with form data",
        "operationId": "Item(Product,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Product({id})/children": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get children of Product object by ID",
        "description": "Returns all child objects of a Product object",
        "operationId": "Item(Product,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Product({id})/references": {
      "get": {
        "tags": [
          "Product"
        ],
        "summary": "Get children of Product object by ID",
        "description": "Returns all child objects of a Product object",
        "operationId": "Item(Product,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Location": {
      "get": {
        "tags": [
          "Location"
        ],
        "summary": "Get list of Location",
        "operationId": "item(Location).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Location"
        ],
        "summary": "Add a new Location",
        "operationId": "Item(Location).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Location({id})": {
      "get": {
        "tags": [
          "Location"
        ],
        "summary": "Find Location by ID",
        "description": "Returns a single Location object",
        "operationId": "Item(Location,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Location"
        ],
        "summary": "Updates a Location with form data",
        "operationId": "Item(Location,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Location"
        ],
        "summary": "Updates a Location",
        "operationId": "Item(Location,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Location"
        ],
        "summary": "Deletes a Location",
        "operationId": "Item(Location,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Location({id})/file": {
      "post": {
        "tags": [
          "Location"
        ],
        "summary": "Adds an attachement to a Location object with form data",
        "operationId": "Item(Location,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/Location({id})/children": {
      "get": {
        "tags": [
          "Location"
        ],
        "summary": "Get children of Location object by ID",
        "description": "Returns all child objects of a Location object",
        "operationId": "Item(Location,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/Location({id})/references": {
      "get": {
        "tags": [
          "Location"
        ],
        "summary": "Get children of Location object by ID",
        "description": "Returns all child objects of a Location object",
        "operationId": "Item(Location,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System": {
      "get": {
        "tags": [
          "dms_System"
        ],
        "summary": "Get list of dms_System",
        "operationId": "item(dms_System).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_System"
        ],
        "summary": "Add a new dms_System",
        "operationId": "Item(dms_System).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System({id})": {
      "get": {
        "tags": [
          "dms_System"
        ],
        "summary": "Find dms_System by ID",
        "description": "Returns a single dms_System object",
        "operationId": "Item(dms_System,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_System"
        ],
        "summary": "Updates a dms_System with form data",
        "operationId": "Item(dms_System,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "dms_System"
        ],
        "summary": "Updates a dms_System",
        "operationId": "Item(dms_System,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "dms_System"
        ],
        "summary": "Deletes a dms_System",
        "operationId": "Item(dms_System,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System({id})/file": {
      "post": {
        "tags": [
          "dms_System"
        ],
        "summary": "Adds an attachement to a dms_System object with form data",
        "operationId": "Item(dms_System,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/dms_System({id})/children": {
      "get": {
        "tags": [
          "dms_System"
        ],
        "summary": "Get children of dms_System object by ID",
        "description": "Returns all child objects of a dms_System object",
        "operationId": "Item(dms_System,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System({id})/references": {
      "get": {
        "tags": [
          "dms_System"
        ],
        "summary": "Get children of dms_System object by ID",
        "description": "Returns all child objects of a dms_System object",
        "operationId": "Item(dms_System,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System({id})/Subsystem": {
      "get": {
        "tags": [
          "dms_System",
          "System"
        ],
        "summary": "Find dms_System by ID and selects all of schema System",
        "description": "Returns a list of Subsystem",
        "operationId": "Item(dms_System,id).link(Subsystem,get)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_System"
        ],
        "summary": "Adds an attachement to a dms_System object with form data",
        "operationId": "Item(dms_System,id).link(Subsystem,post)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_System({id})/Subsystem({linkId})": {
      "delete": {
        "tags": [
          "dms_System",
          "System"
        ],
        "summary": "Find dms_System by ID and selects all of schema System",
        "description": "Returns a list of Subsystem",
        "operationId": "Item(dms_System,id).link(Subsystem,delete)",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Location": {
      "get": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Get list of dms_Location",
        "operationId": "item(dms_Location).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Add a new dms_Location",
        "operationId": "Item(dms_Location).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Location({id})": {
      "get": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Find dms_Location by ID",
        "description": "Returns a single dms_Location object",
        "operationId": "Item(dms_Location,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Updates a dms_Location with form data",
        "operationId": "Item(dms_Location,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Updates a dms_Location",
        "operationId": "Item(dms_Location,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Deletes a dms_Location",
        "operationId": "Item(dms_Location,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Location({id})/file": {
      "post": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Adds an attachement to a dms_Location object with form data",
        "operationId": "Item(dms_Location,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/dms_Location({id})/children": {
      "get": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Get children of dms_Location object by ID",
        "description": "Returns all child objects of a dms_Location object",
        "operationId": "Item(dms_Location,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Location({id})/references": {
      "get": {
        "tags": [
          "dms_Location"
        ],
        "summary": "Get children of dms_Location object by ID",
        "description": "Returns all child objects of a dms_Location object",
        "operationId": "Item(dms_Location,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Group": {
      "get": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Get list of dms_Group",
        "operationId": "item(dms_Group).find",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Add a new dms_Group",
        "operationId": "Item(dms_Group).add",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Group({id})": {
      "get": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Find dms_Group by ID",
        "description": "Returns a single dms_Group object",
        "operationId": "Item(dms_Group,id).get",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Updates a dms_Group with form data",
        "operationId": "Item(dms_Group,id).post",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Updates a dms_Group",
        "operationId": "Item(dms_Group,id).patch",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Deletes a dms_Group",
        "operationId": "Item(dms_Group,id).delete",
        "security": [
          {
            "default_auth": [
              "write:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Group({id})/file": {
      "post": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Adds an attachement to a dms_Group object with form data",
        "operationId": "Item(dms_Group,id).file(post)",
        "security": [
          {
            "aim_auth": [
              "file.write"
            ]
          }
        ]
      }
    },
    "/dms_Group({id})/children": {
      "get": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Get children of dms_Group object by ID",
        "description": "Returns all child objects of a dms_Group object",
        "operationId": "Item(dms_Group,id).children()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    },
    "/dms_Group({id})/references": {
      "get": {
        "tags": [
          "dms_Group"
        ],
        "summary": "Get children of dms_Group object by ID",
        "description": "Returns all child objects of a dms_Group object",
        "operationId": "Item(dms_Group,id).references()",
        "security": [
          {
            "default_auth": [
              "write:web",
              "read:web",
              "write:all",
              "admin:write",
              "write:admin"
            ]
          }
        ]
      }
    }
  },
  "components": {
  },
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "Messages"
    },
    {
      "name": "Files"
    },
    {
      "name": "Company"
    },
    {
      "name": "Contact"
    },
    {
      "name": "Map"
    },
    {
      "name": "Website"
    },
    {
      "name": "Webpage"
    },
    {
      "name": "Schema"
    },
    {
      "name": "Message"
    },
    {
      "name": "Schakelbericht"
    },
    {
      "name": "System"
    },
    {
      "name": "Attribute"
    },
    {
      "name": "ControlIO"
    },
    {
      "name": "Device"
    },
    {
      "name": "Product"
    },
    {
      "name": "Location"
    },
    {
      "name": "dms_System"
    },
    {
      "name": "dms_Location"
    },
    {
      "name": "dms_Group"
    }
  ],
  "security": [
    {
      "api_key": []
    }
  ]
}